// Generated by CoffeeScript 1.10.0
(function() {
  var Main;

  Main = (function() {
    function Main() {
      this.initBackground();
      this.initTop();
    }

    Main.prototype.initTop = function() {
      var counter, interval_count, interval_sec;
      interval_sec = 0.5;
      interval_count = 5;
      counter = 0;
      return setInterval((function(_this) {
        return function() {
          counter += 1;
          if (counter % interval_count === 0) {
            return $('#top img.scroll_down').css('opacity', '0');
          } else {
            return $('#top img.scroll_down').css('opacity', '1');
          }
        };
      })(this), interval_sec * 1000 / interval_count);
    };

    Main.prototype.initBackground = function() {
      var rotation;
      rotation = 0;
      return setInterval((function(_this) {
        return function() {
          rotation += 1;
          return $('#base img.rolling').css('transform', "rotate(" + rotation + "deg)");
        };
      })(this), 33);
    };

    return Main;

  })();

  $(function() {
    return new Main;
  });

}).call(this);
